hawkular/hawkular-commons

embedded-cassandra/embedded-cassandra-service/pom.xml, pom.xml
[Don't merge yet] - depends on hawkular-parent 26 that needs to be released yet
=> Upgrade to hawkular-parent 26

hawkular-nest/hawkular-nest-feature-pack/src/main/resources/modules/org/hawkular/commons/cassandra-driver/main/module.xml
Fix for a blocker issue on alerts scenario.
=> HAWKULAR-891 Missing dependency on C* driver module

hawkular-bus/hawkular-bus-common/src/main/java/org/hawkular/bus/common/consumer/RPCBasicMessageListener.java
RPC message listener should not close listening connection instead it should close connection of a response.
PR sent to original repository: https://github.com/hawkular/hawkular-bus/pull/56
=> RPC message listener -fix response connection closing

hawkular-command-gateway/hawkular-command-gateway-api/src/main/resources/schema/DeployApplicationRequest.schema.json, hawkular-command-gateway/hawkular-command-gateway-api/src/main/resources/schema/UndeployApplicationRequest.schema.json, hawkular-command-gateway/hawkular-command-gateway-api/src/main/resources/schema/UndeployApplicationResponse.schema.json
also adds serverGroups to deploy for domain support
=> HWKAGENT-101 undeploy

hawkular-rest-status/pom.xml, hawkular-rest-status/src/main/java/org/hawkular/commons/rest/status/RestStatusHandler.java, hawkular-tenant-jaxrs-filter/pom.xml, hawkular-tenant-jaxrs-filter/src/main/java/org/hawkular/jaxrs/filter/tenant/TenantFeature.java, hawkular-tenant-jaxrs-filter/src/main/java/org/hawkular/jaxrs/filter/tenant/TenantFilter.java, hawkular-tenant-jaxrs-filter/src/main/java/org/hawkular/jaxrs/filter/tenant/TenantRequired.java, hawkular-tenant-jaxrs-filter/src/test/java/org/hawkular/jaxrs/filter/tenant/DefaultRequiresHeaderTest.java, hawkular-tenant-jaxrs-filter/src/test/java/org/hawkular/jaxrs/filter/tenant/FooApp.java, hawkular-tenant-jaxrs-filter/src/test/java/org/hawkular/jaxrs/filter/tenant/FooEndpoint.java, hawkular-tenant-jaxrs-filter/src/test/java/org/hawkular/jaxrs/filter/tenant/FooNoTenantEndpoint.java, hawkular-tenant-jaxrs-filter/src/test/resources/arquillian.xml, pom.xml
And skip it for the Status filter
=> HWKALERTS-148 HWKINVENT-184 - Common Tenant Filter

hawkular-command-gateway/hawkular-command-gateway-api/src/main/resources/schema/DisableApplicationRequest.schema.json, hawkular-command-gateway/hawkular-command-gateway-api/src/main/resources/schema/DisableApplicationResponse.schema.json, hawkular-command-gateway/hawkular-command-gateway-api/src/main/resources/schema/EnableApplicationRequest.schema.json, hawkular-command-gateway/hawkular-command-gateway-api/src/main/resources/schema/EnableApplicationResponse.schema.json, hawkular-command-gateway/hawkular-command-gateway-api/src/main/resources/schema/RestartApplicationRequest.schema.json, hawkular-command-gateway/hawkular-command-gateway-api/src/main/resources/schema/RestartApplicationResponse.schema.json
- Add the necessary request/response schema.json
@jmazzitelli Please review
=> HAWKULAR-1108 Support Enable/Disable/Restart Deployment request/response

hawkular-cors-jaxrs-filter/src/main/java/org/hawkular/jaxrs/filter/cors/AbstractOriginValidation.java
@jpkrohling could you please review?
=> CORS filter allow empty allowed origins

email/pom.xml, embedded-cassandra/embedded-cassandra-service/pom.xml, embedded-cassandra/embedded-cassandra-war/pom.xml, embedded-cassandra/pom.xml, hawkular-bus/hawkular-bus-common/pom.xml, hawkular-bus/hawkular-bus-feature-pack/pom.xml, hawkular-bus/hawkular-bus-mdb/pom.xml, hawkular-bus/hawkular-bus-rest-client/pom.xml, hawkular-bus/pom.xml, hawkular-command-gateway/hawkular-command-gateway-api/pom.xml, hawkular-command-gateway/hawkular-command-gateway-itest/pom.xml, hawkular-command-gateway/hawkular-command-gateway-war/pom.xml, hawkular-command-gateway/pom.xml, hawkular-cors-jaxrs-filter/pom.xml, hawkular-inventory-paths/pom.xml, hawkular-nest/hawkular-nest-feature-pack/pom.xml, hawkular-nest/hawkular-nest-itest/pom.xml, hawkular-nest/hawkular-nest-wf-extension/pom.xml, hawkular-nest/pom.xml, hawkular-rest-status/pom.xml, hawkular-tenant-jaxrs-filter/pom.xml, pom.xml, templates/pom.xml
@pilhuhn or @jmazzitelli Please review/merge.
=> Prepare poms for 1st release of 2017

hawkular-command-gateway/hawkular-command-gateway-api/src/main/resources/schema/UpdateCollectionIntervalsRequest.schema.json, hawkular-command-gateway/hawkular-command-gateway-api/src/main/resources/schema/UpdateCollectionIntervalsResponse.schema.json
@jmazzitelli Here are the proposed request/response decls for the pending UpdateCollectionIntervalsCommand support in the agent.  Please review.
=> Hawkular-1157 Add request/response for updating collection intervals

hawkular-client-api/pom.xml, hawkular-client-api/src/main/java/org/hawkular/client/api/Notification.java, hawkular-client-api/src/main/java/org/hawkular/client/api/NotificationType.java, pom.xml
- adds support for hawkular-commons:hawkular-client-api
@jmazzitelli This is the commons addition for the new client jar supporting services rest-api
=> HAWKULAR-1208 Add shared client support for agent and services

pom.xml, utils/pom.xml, utils/src/main/java/org/hawkular/commons/log/MsgLogger.java, utils/src/main/java/org/hawkular/commons/log/MsgLogging.java, utils/src/main/java/org/hawkular/commons/properties/HawkularProperties.java, vertx/rest-api/pom.xml, vertx/rest-api/src/main/java/org/hawkular/handlers/BaseApplication.java, vertx/rest-api/src/main/java/org/hawkular/handlers/RestEndpoint.java, vertx/rest-api/src/main/java/org/hawkular/handlers/RestHandler.java, vertx/server/pom.xml, vertx/server/src/main/java/org/hawkular/HandlersManager.java, vertx/server/src/main/java/org/hawkular/HawkularServer.java, vertx/server/src/main/java/org/hawkular/HawkularServerMBean.java
Common logging & properties utils
Rest Api for Vert.X/Netty handlers
Common Vert.X/Netty server loader
As commented @stefannegrea. 
Please could you review and merge ?
I have a local alerting branch working with them, I would need a release in orther to link the dependencies (or just a merge with temporal srcdeps).
/cc @jshaughn
=> Extract shared artifacts from Alerting

vertx/server/src/main/java/org/hawkular/HandlersManager.java
This PR fixes how endpoints are internally stored, adding the class into the relative endpoint.
So, multiple relative enpoints on different applications are now supported.
=> Support relative endpoints on multiple applications

vertx/server/src/main/java/org/hawkular/HandlersManager.java
- Add allowed methods
- change property name from hawkular.cors-url to hawkular.cors-origin-pattern
- this better reflects what the value actually is. It is a pattern and supports
this like, .*localhost:.*
I carried over the defaults we used in the jaxrs cors support module
in commons.
=> CORS Support

hawkular-inventory-parent/hawkular-inventory-api/src/main/java/org/hawkular/inventory/api/model/Metric.java
- Immutable model
- Model content initialized from full-args ctor
- Relational content is referred in two ways:
- primarily with ids, stored in model
- with lazy-loaded object reference
=> Model proposal

hawkular-inventory-parent/hawkular-inventory-api/src/main/java/org/hawkular/inventory/api/Import.java, hawkular-inventory-parent/hawkular-inventory-api/src/main/java/org/hawkular/inventory/api/InventoryService.java, hawkular-inventory-parent/hawkular-inventory-api/src/main/java/org/hawkular/inventory/api/ResourceNode.java, hawkular-inventory-parent/hawkular-inventory-model/src/main/java/org/hawkular/inventory/model/Metric.java, hawkular-inventory-parent/hawkular-inventory-model/src/main/java/org/hawkular/inventory/model/Resource.java, hawkular-inventory-parent/hawkular-inventory-model/src/test/java/org/hawkular/inventory/model/ResourceTest.java, hawkular-inventory-parent/hawkular-inventory-service/pom.xml, hawkular-inventory-parent/hawkular-inventory-service/src/main/java/org/hawkular/inventory/handlers/InventoryHandlers.java, hawkular-inventory-parent/hawkular-inventory-service/src/main/java/org/hawkular/inventory/service/InventoryConfig.java, hawkular-inventory-parent/hawkular-inventory-service/src/main/java/org/hawkular/inventory/service/InventoryServiceIspn.java, hawkular-inventory-parent/hawkular-inventory-service/src/main/java/org/hawkular/inventory/service/IspnPK.java, hawkular-inventory-parent/hawkular-inventory-service/src/test/java/org/hawkular/inventory/service/InventoryRestTest.java, hawkular-inventory-parent/hawkular-inventory-service/src/test/java/org/hawkular/inventory/service/InventoryServiceIspnTest.java, hawkular-inventory-parent/hawkular-inventory-service/src/test/resources/ispn-local-8.2.xml, hawkular-inventory-parent/hawkular-inventory-service/src/test/resources/test.yml
- REST API: manage delete
- Serve agent config files
- Remove Metrics index in ISPN / not searchable by metric anymore (metrics are now directly attached to their resource)
- Service unit tests
=> Inventory updates

hawkular-inventory-parent/hawkular-inventory-api/src/main/java/org/hawkular/inventory/api/InventoryService.java, hawkular-inventory-parent/hawkular-inventory-model/pom.xml, hawkular-inventory-parent/hawkular-inventory-model/src/main/java/org/hawkular/inventory/model/Resource.java, hawkular-inventory-parent/hawkular-inventory-model/src/main/java/org/hawkular/inventory/model/ResourceType.java, hawkular-inventory-parent/hawkular-inventory-service/pom.xml, hawkular-inventory-parent/hawkular-inventory-service/src/main/java/org/hawkular/inventory/handlers/InventoryHandlers.java, hawkular-inventory-parent/hawkular-inventory-service/src/main/java/org/hawkular/inventory/service/Inventory.java, hawkular-inventory-parent/hawkular-inventory-service/src/main/java/org/hawkular/inventory/service/InventoryConfig.java, hawkular-inventory-parent/hawkular-inventory-service/src/main/java/org/hawkular/inventory/service/InventoryServiceIspn.java, hawkular-inventory-parent/hawkular-inventory-service/src/main/resources/hawkular-inventory-ispn.xml, hawkular-inventory-parent/hawkular-inventory-service/src/test/java/org/hawkular/inventory/service/InventoryRestTest.java, pom.xml
- Upgrades to ISPN 9.
- Add support to add collections in a single step (thinking on import operations).
- Start testing eviction modes and large scenarios to find potential blockers or anti-patterns.
=> Migrate to ISPN 9

hawkular-inventory-parent/hawkular-inventory-api/src/main/java/org/hawkular/inventory/api/InventoryService.java, hawkular-inventory-parent/hawkular-inventory-api/src/main/java/org/hawkular/inventory/api/JacksonDeserializer.java, hawkular-inventory-parent/hawkular-inventory-api/src/main/java/org/hawkular/inventory/api/ResourceNode.java, hawkular-inventory-parent/hawkular-inventory-api/src/main/java/org/hawkular/inventory/api/ResultSet.java, hawkular-inventory-parent/hawkular-inventory-api/src/test/java/org/hawkular/inventory/api/JsonTest.java, hawkular-inventory-parent/hawkular-inventory-model/src/main/java/org/hawkular/inventory/model/Resource.java, hawkular-inventory-parent/hawkular-inventory-service/src/main/java/org/hawkular/inventory/handlers/InventoryHandlers.java, hawkular-inventory-parent/hawkular-inventory-service/src/main/java/org/hawkular/inventory/service/InventoryServiceIspn.java, hawkular-inventory-parent/hawkular-inventory-service/src/main/resources/hawkular-inventory-ispn.xml, hawkular-inventory-parent/hawkular-inventory-service/src/test/java/org/hawkular/inventory/service/InventoryRestTest.java, hawkular-inventory-parent/hawkular-inventory-service/src/test/java/org/hawkular/inventory/service/InventoryServiceIspnTest.java, hawkular-inventory-parent/hawkular-inventory-service/src/test/resources/hawkular-inventory-ispn-test.xml, hawkular-inventory-parent/hawkular-inventory-service/src/test/resources/standalone.xsl
- Changed API to support pagination.
- Improvements on performance: tweak indexes and configuration.
- Additional tests to get measures on big scenarios.
=> Support for pagination and improvements in performance

hawkular-inventory-parent/hawkular-inventory-api/src/main/java/org/hawkular/inventory/api/InventoryService.java, hawkular-inventory-parent/hawkular-inventory-service/pom.xml, hawkular-inventory-parent/hawkular-inventory-service/src/main/java/org/hawkular/inventory/service/InventoryConfig.java, hawkular-inventory-parent/hawkular-inventory-service/src/main/java/org/hawkular/inventory/service/InventoryResource.java, hawkular-inventory-parent/hawkular-inventory-service/src/main/java/org/hawkular/inventory/service/InventoryResourceType.java, hawkular-inventory-parent/hawkular-inventory-service/src/main/java/org/hawkular/inventory/service/InventoryServiceIspn.java, hawkular-inventory-parent/hawkular-inventory-service/src/main/resources/hawkular-inventory-ispn.xml, hawkular-inventory-parent/hawkular-inventory-service/src/test/java/org/hawkular/inventory/service/InventoryRestTest.java, hawkular-inventory-parent/hawkular-inventory-service/src/test/java/org/hawkular/inventory/service/InventoryServiceIspnTest.java, hawkular-inventory-parent/hawkular-inventory-service/src/test/resources/hawkular-inventory-ispn-test.xml
Support ISPN configuration from standalone/configuration/hawkular folder
Unify some typeId variables
Brought test back to confirm types are not impacted with heavy resource storage.
```
<testcase name="test000_statusIsUp" classname="org.hawkular.inventory.service.InventoryRestTest" time="0.729"/>
<testcase name="test001_importResources" classname="org.hawkular.inventory.service.InventoryRestTest" time="0.487"/>
<testcase name="test002_shouldFindResourcesById" classname="org.hawkular.inventory.service.InventoryRestTest" time="0.259"/>
<testcase name="test003_shouldNotFindResourcesById" classname="org.hawkular.inventory.service.InventoryRestTest" time="0.238"/>
<testcase name="test004_shouldGetTopResources" classname="org.hawkular.inventory.service.InventoryRestTest" time="0.568"/> …
```
=> Split Resource and ResourceType on different caches

hawkular-inventory-parent/hawkular-inventory-model/src/main/java/org/hawkular/inventory/model/Resource.java
I'm not sure why the integration tests pass, but @jmazzitelli found an issue about that while using /import endpoint from the agent
=> Add JsonIgnore annotation wherever necessary

hawkular-inventory-parent/hawkular-inventory-api/src/main/java/org/hawkular/inventory/api/InventoryService.java, hawkular-inventory-parent/hawkular-inventory-service/src/main/java/org/hawkular/inventory/handlers/InventoryHandlers.java, hawkular-inventory-parent/hawkular-inventory-service/src/main/java/org/hawkular/inventory/service/InventoryServiceIspn.java, hawkular-inventory-parent/hawkular-inventory-service/src/test/java/org/hawkular/inventory/service/InventoryPerfTest.java, hawkular-inventory-parent/hawkular-inventory-service/src/test/java/org/hawkular/inventory/service/InventoryRestTest.java, hawkular-inventory-parent/hawkular-inventory-service/src/test/java/org/hawkular/inventory/service/InventoryServiceIspnTest.java
so that itests run better
Also add "@get /types/{typeId}" endpoint that was curiously missing
=> Add delete all endpoints

hawkular-inventory-parent/hawkular-inventory-api/src/main/java/org/hawkular/inventory/api/model/Resource.java, hawkular-inventory-parent/hawkular-inventory-api/src/main/java/org/hawkular/inventory/api/model/ResourceNode.java, hawkular-inventory-parent/hawkular-inventory-api/src/main/java/org/hawkular/inventory/api/model/ResourceWithType.java, hawkular-inventory-parent/hawkular-inventory-api/src/test/java/org/hawkular/inventory/api/model/BuilderTest.java, hawkular-inventory-parent/hawkular-inventory-api/src/test/java/org/hawkular/inventory/api/model/JsonTest.java, hawkular-inventory-parent/hawkular-inventory-api/src/test/java/org/hawkular/inventory/api/model/ResourceTest.java, hawkular-inventory-parent/hawkular-inventory-service/src/test/java/org/hawkular/inventory/Resources.java, hawkular-inventory-parent/hawkular-inventory-service/src/test/java/org/hawkular/inventory/handlers/InventoryPerfTest.java, hawkular-inventory-parent/hawkular-inventory-service/src/test/java/org/hawkular/inventory/handlers/InventoryRestTest.java, hawkular-inventory-parent/hawkular-inventory-service/src/test/java/org/hawkular/inventory/service/InventoryServiceIspnTest.java
Also refactor resource class constructors so that they're consistent one another
=> Add config map in resources

hawkular-inventory-parent/hawkular-inventory-ui/src/main/ui/src/resources/resources-controller.js, hawkular-inventory-parent/hawkular-inventory-ui/src/main/ui/src/resources/resources.html
- fix font load issue by overriding all fonts with available
font awesome (fa) fonts
- partially fix not selection by using star icon to indicate
selected resource and adding selectability to parent nodes.
- note that highlighting the selected node is not working for
reasons I don't understand (maybe color choice?).
- get tree and resource detail (textarea) to have reasonable height.
- trim html to only what is required
=> Show Resource Detail

.travis.swagger.sh, .travis.yml, hawkular-inventory-parent/hawkular-inventory-api/pom.xml, hawkular-inventory-parent/hawkular-inventory-api/src/main/java/org/hawkular/inventory/api/model/Inventory.java, hawkular-inventory-parent/hawkular-inventory-api/src/main/java/org/hawkular/inventory/api/model/Metric.java, hawkular-inventory-parent/hawkular-inventory-api/src/main/java/org/hawkular/inventory/api/model/Operation.java, hawkular-inventory-parent/hawkular-inventory-api/src/main/java/org/hawkular/inventory/api/model/RawResource.java, hawkular-inventory-parent/hawkular-inventory-api/src/main/java/org/hawkular/inventory/api/model/Resource.java, hawkular-inventory-parent/hawkular-inventory-api/src/main/java/org/hawkular/inventory/api/model/ResourceNode.java, hawkular-inventory-parent/hawkular-inventory-api/src/main/java/org/hawkular/inventory/api/model/ResourceType.java, hawkular-inventory-parent/hawkular-inventory-api/src/main/java/org/hawkular/inventory/api/model/ResultSet.java, hawkular-inventory-parent/hawkular-inventory-service/pom.xml, hawkular-inventory-parent/hawkular-inventory-service/src/main/java/org/hawkular/inventory/handlers/InventoryHandlers.java, hawkular-inventory-parent/hawkular-inventory-service/src/main/java/org/hawkular/inventory/handlers/ResponseUtil.java, hawkular-inventory-parent/hawkular-inventory-service/src/main/rest-doc/api-to-doc.groovy, hawkular-inventory-parent/hawkular-inventory-service/src/main/rest-doc/base.adoc, hawkular-inventory-parent/hawkular-inventory-service/src/main/rest-doc/generate-api.groovy, utils/src/main/java/org/hawkular/commons/doc/DocConstants.java, utils/src/main/java/org/hawkular/commons/doc/DocEndpoint.java, utils/src/main/java/org/hawkular/commons/doc/DocModel.java, utils/src/main/java/org/hawkular/commons/doc/DocModelProperty.java, utils/src/main/java/org/hawkular/commons/doc/DocParameter.java, utils/src/main/java/org/hawkular/commons/doc/DocParameters.java, utils/src/main/java/org/hawkular/commons/doc/DocPath.java, utils/src/main/java/org/hawkular/commons/doc/DocResponse.java, utils/src/main/java/org/hawkular/commons/doc/DocResponses.java
- Move to commons lightweight documentation annotations used in Alerting 2.x
- Adjust groovy script to support generic type use cases
- Prepare travis scripts to upload documentation into github
Note that this PR won't publish documentation into hawkular.github.io yet for this it should be decided when to upload doc (on every commit, on releases only, from one branch or another branch, etc).
Once this is decided, secure settings should be updated into travis.yml but all scripts should be working.
=> HAWKULAR-1263 Document the Inventory REST API

hawkular-inventory-parent/hawkular-inventory-service/pom.xml, hawkular-inventory-parent/hawkular-inventory-service/src/main/java/org/hawkular/inventory/handlers/InventoryHandlers.java, hawkular-inventory-parent/hawkular-inventory-service/src/main/java/org/hawkular/inventory/handlers/RESTPathDiscovery.java, hawkular-inventory-parent/hawkular-inventory-service/src/main/java/org/hawkular/inventory/handlers/ResourcesDiscovery.java
Add resteasy dependency (provided) for REST endpoints introspection
=> HAWKULAR-1264 Rest API self discovery

hawkular-inventory-parent/hawkular-inventory-api/src/main/java/org/hawkular/inventory/api/InventoryService.java, hawkular-inventory-parent/hawkular-inventory-api/src/main/java/org/hawkular/inventory/api/model/InventoryHealth.java, hawkular-inventory-parent/hawkular-inventory-service/src/main/java/org/hawkular/inventory/handlers/InventoryHandlers.java, hawkular-inventory-parent/hawkular-inventory-service/src/main/java/org/hawkular/inventory/log/MsgLogger.java, hawkular-inventory-parent/hawkular-inventory-service/src/main/java/org/hawkular/inventory/service/InventoryConfig.java, hawkular-inventory-parent/hawkular-inventory-service/src/main/java/org/hawkular/inventory/service/InventoryLocation.java, hawkular-inventory-parent/hawkular-inventory-service/src/main/java/org/hawkular/inventory/service/InventoryServiceIspn.java, hawkular-inventory-parent/hawkular-inventory-service/src/main/java/org/hawkular/inventory/service/InventoryStats.java, hawkular-inventory-parent/hawkular-inventory-service/src/main/java/org/hawkular/inventory/service/InventoryStatsMBean.java, hawkular-inventory-parent/hawkular-inventory-service/src/main/resources/hawkular-inventory-ispn.xml, hawkular-inventory-parent/hawkular-inventory-service/src/test/java/org/hawkular/inventory/handlers/InventoryPerfTest.java, hawkular-inventory-parent/hawkular-inventory-service/src/test/java/org/hawkular/inventory/service/InventoryServiceIspnTest.java, hawkular-inventory-parent/hawkular-inventory-service/src/test/resources/hawkular-inventory-ispn-test.xml
- Memory, disk, cpu and inventory stats
=> HAWKULAR-1273 Inventory Monitoring

hawkular-inventory-parent/hawkular-inventory-api/src/main/java/org/hawkular/inventory/api/model/Resource.java, hawkular-inventory-parent/hawkular-inventory-api/src/main/java/org/hawkular/inventory/api/model/ResourceNode.java, hawkular-inventory-parent/hawkular-inventory-api/src/test/java/org/hawkular/inventory/api/model/JsonTest.java, hawkular-inventory-parent/hawkular-inventory-service/src/main/java/org/hawkular/inventory/handlers/InventoryHandlers.java, hawkular-inventory-parent/hawkular-inventory-service/src/test/java/org/hawkular/inventory/handlers/InventoryRestTest.java
For use case, cf. https://github.com/hawkular/hawkular-client-ruby/pull/239#discussion_r145869642
=> Expose parentId in model, add REST endpoint to get parent

hawkular-inventory-parent/hawkular-inventory-api/src/main/java/org/hawkular/inventory/api/model/Metric.java, hawkular-inventory-parent/hawkular-inventory-api/src/test/java/org/hawkular/inventory/api/model/BuilderTest.java, hawkular-inventory-parent/hawkular-inventory-api/src/test/java/org/hawkular/inventory/api/model/JsonTest.java, hawkular-inventory-parent/hawkular-inventory-api/src/test/java/org/hawkular/inventory/api/model/ResourceNodeTest.java, hawkular-inventory-parent/hawkular-inventory-api/src/test/java/org/hawkular/inventory/api/model/ResourceTest.java, hawkular-inventory-parent/hawkular-inventory-itest/src/test/java/org/hawkular/inventory/Resources.java, hawkular-inventory-parent/hawkular-inventory-itest/src/test/java/org/hawkular/inventory/handlers/InventoryPerfTest.java, hawkular-inventory-parent/hawkular-inventory-service/src/test/java/org/hawkular/inventory/Resources.java
- Rename "name" => "displayName"
- Add "family"
- Add "labels"
- Remove unused "type"
=> Update Metric model for Prometheus

hawkular-inventory-parent/hawkular-inventory-ui/src/main/ui/src/resources/resources-controller.js
Note that there are still some issues between the
labels defined on the metrics and the labels being applied
on the time series. Until that is cleared up not
all of the graphs may appear as expected.
=> Fix some label handling.  Also, add sorting to metrics drop down.

hawkular-inventory-parent/hawkular-inventory-itest/pom.xml, hawkular-inventory-parent/hawkular-inventory-service/src/main/java/org/hawkular/inventory/service/InventoryConfig.java
=> HAWKULAR-1326 Create prometheus config folder before cache init

hawkular-inventory-parent/hawkular-inventory-service/src/main/resources/wildfly-10-jmx-exporter.yml
see https://issues.jboss.org/browse/HAWKULAR-1321
we use this in https://github.com/hawkular/hawkular-agent/pull/406
=> support our platform metrics again

hawkular-inventory-parent/hawkular-inventory-ui/src/main/ui/src/resources/resources-controller.js, hawkular-inventory-parent/hawkular-inventory-ui/src/main/ui/src/resources/resources-service.js, hawkular-inventory-parent/hawkular-inventory-ui/src/main/ui/src/resources/resources.html
- Add feedid to root node labeling
- Add feedid filtering
=> Inventory UI - Feed Work

hawkular-inventory-parent/hawkular-inventory-itest/src/test/java/org/hawkular/inventory/handlers/InventoryRestTest.java, hawkular-inventory-parent/hawkular-inventory-service/src/main/resources/eap-6-jmx-exporter.yml, hawkular-inventory-parent/hawkular-inventory-service/src/main/resources/hawkular-inventory-prometheus-scrape-config.yaml
Adjust scrape config to versioning types
=> HAWKULAR-1320 Add a EAP6 jmx exporter

hawkular-inventory-parent/hawkular-inventory-ui/src/main/ui/src/resources/resources-controller.js, hawkular-inventory-parent/hawkular-inventory-ui/src/main/ui/src/types/types-controller.js, hawkular-inventory-parent/hawkular-inventory-ui/src/main/ui/src/types/types.html
- Add text-based client-side filter of types list
- Also, maintain feedId filter dropdown entries between
'All Feeds' fetches.
=> Inventory UI - Types Filter

hawkular-inventory-parent/hawkular-inventory-service/src/main/java/org/hawkular/inventory/log/MsgLogger.java, hawkular-inventory-parent/hawkular-inventory-service/src/main/java/org/hawkular/inventory/service/InventoryServiceIspn.java, hawkular-inventory-parent/hawkular-inventory-service/src/test/java/org/hawkular/inventory/service/InventoryServiceIspnTest.java
…  when Agent is removed from inventory
=> HAWKULAR-1329 Remove Prometheus scrape endpoint

hawkular-inventory-parent/hawkular-inventory-ui/src/main/ui/src/types/types-controller.js, hawkular-inventory-parent/hawkular-inventory-ui/src/main/ui/src/types/types.html
- remove config. resource types don't have config, only resources
- fix bug with count of properties
=> Types List Tweaks

hawkular-inventory-parent/hawkular-inventory-service/src/main/resources/EAP6-jmx-exporter.yml, hawkular-inventory-parent/hawkular-inventory-service/src/main/resources/WF10-jmx-exporter.yml
This is the counter part of PR 
https://github.com/hawkular/hawkular-agent/pull/427
It moves the special management-root MBean into the instances list.
=> HAWKULAR-1349 Move management-root MBean to instances list
