embedded-cassandra/embedded-cassandra-service/src/main/java/org/hawkular/commons/cassandra/EmbeddedCassandraService.java
embedded-cassandra/embedded-cassandra-service/src/main/java/org/hawkular/commons/cassandra/EmbeddedConstants.java

This is/can be used to prevent/enable starting the embedded C* database from an env variable.
This way, when using external C* nodes on Docker one can start the docker image with an env of
`-e HAWKULAR_BACKEND=""` to prevent the startup of embedded C*.

Allow to override the backend sys-prop from the environment.

---

embedded-cassandra/embedded-cassandra-service/src/main/java/org/hawkular/commons/cassandra/EmbeddedCassandraService.java

In C* 2.2.0 a call to CassandraDaemon.deactivate() will call to a System.exit(0) if runManaged flag was not activated.
This may lead in troubles if when this call is invoked inside an app server.

Create CassandraDaemon as runManaged

---

hawkular-nest/hawkular-nest-feature-pack/pom.xml
hawkular-nest/hawkular-nest-feature-pack/src/main/xsl/subsystem-templates/hawkular-nest-logging.xsl
hawkular-nest/hawkular-nest-itest/pom.xml

... by modifying system properties.
This is mostly useful to limit the output of the integration tests run
in Travis environment.

Provide a way to customize the root logger level as well as the console log level

---

hawkular-inventory-paths/src/main/java/org/hawkular/inventory/paths/Path.java
hawkular-inventory-paths/src/test/java/org/hawkular/inventory/paths/CanonicalPathTest.java

This cropped up during some inventory changes.

Handle unknown expected type of partially untyped paths.

---

hawkular-command-gateway/hawkular-command-gateway-itest/src/test/java/org/hawkular/cmdgw/ws/test/AbstractCommandITest.java
hawkular-command-gateway/hawkular-command-gateway-itest/src/test/java/org/hawkular/cmdgw/ws/test/ClientConfig.java
hawkular-command-gateway/hawkular-command-gateway-itest/src/test/java/org/hawkular/cmdgw/ws/test/EchoCommandITest.java
hawkular-command-gateway/hawkular-command-gateway-itest/src/test/java/org/hawkular/cmdgw/ws/test/TestWebSocketClient.java

this helps for those tests that don't use arquillian

refactor this so the static configuration for the client does not require being in the arquillian test hierarchy.

---

hawkular-command-gateway/hawkular-command-gateway-war/pom.xml
hawkular-command-gateway/hawkular-command-gateway-war/src/main/webapp/WEB-INF/jboss-deployment-structure.xml

The cmd gateway war should not package it, and it should
declare a dependency in jboss-deployment-structure.xml

Hawkular-inventory-paths is provided by the nest.

---

hawkular-command-gateway/hawkular-command-gateway-api/src/main/resources/schema/FeedWebSocketClosedEvent.schema.json
hawkular-command-gateway/hawkular-command-gateway-war/src/main/java/org/hawkular/cmdgw/command/ws/server/FeedWebSocket.java
hawkular-command-gateway/hawkular-command-gateway-war/src/main/java/org/hawkular/cmdgw/log/MsgLogger.java

For feeds establishing a websocket connection to the server we
want to detect when the WS is closed, and use that information
to backfill avails for the resources managed by that feed. So,
put a message on the bus that can be picked up by a hawkular-level
(aka glue) listener and actioned on.
@jmazzitelli please review

Related to Hawkular-1101, Backfiller does not honor DOWN availability

---

hawkular-tenant-jaxrs-filter/pom.xml
hawkular-tenant-jaxrs-filter/src/main/java/org/hawkular/jaxrs/filter/tenant/TenantRequired.java

because the `@TenantRequired` is not used for injection or container-managed interception.
Removing it enables us to minimize the dependencies of this module.

@NonBinding is not needed

---

hawkular-command-gateway/hawkular-command-gateway-war/src/main/java/org/hawkular/cmdgw/Constants.java
hawkular-command-gateway/hawkular-command-gateway-war/src/main/java/org/hawkular/cmdgw/command/ws/EventDestinationWsCommand.java
hawkular-command-gateway/hawkular-command-gateway-war/src/main/java/org/hawkular/cmdgw/command/ws/server/FeedWebSocket.java

- Continue publishing command events to HawkularCommandEvent but convert
it to a queue as opposed to a topic, limiting message consumption to a
single handler.
- Change publishing FeedWebSocketClosed events from HawkularCommandEvent
to a new topic, HawkularTopic.  This improves separation of concern,
and maintains topic publishing for this event message.

Hawkular-1104 Multiple Event Issue

---

pom.xml

The 1.3.8 version has a bad POM for jsr305 artifact (incorrect artifactId)
Also this syncs the version with some other projects

Upgrade findbugs 1.3.8 -> 1.3.9

---

hawkular-cors-jaxrs-filter/pom.xml
hawkular-cors-jaxrs-filter/src/main/java/org/hawkular/jaxrs/filter/cors/AbstractCorsResponseFilter.java
hawkular-cors-jaxrs-filter/src/main/java/org/hawkular/jaxrs/filter/cors/AbstractOriginValidation.java
hawkular-cors-jaxrs-filter/src/main/java/org/hawkular/jaxrs/filter/cors/CorsRequestFilter.java
hawkular-cors-jaxrs-filter/src/main/java/org/hawkular/jaxrs/filter/cors/Headers.java
pom.xml

- Because CORS is a general feature that multiple Hawkular component's
REST APIs do, or may, support, add base support in a new commons module.
- We don't have a commons-level configuration utility (we probably
should in order to consolidate hawkular component config).  Because
we don't this is set up such that consuming components can configure
it using their own mechanism.  If we ever have a common config, we
could likely have all the CORS support in commons, with nothing
abstract and needing component-level override.
- Thanks to Stefan, this originates with his code in Hmetrics (which should
now likely leverage this code as well ;)
@stefannegrea Please review

hwkalerts-174 Add CORS support

---

hawkular-command-gateway/hawkular-command-gateway-api/src/main/resources/schema/AddDatasourceResponse.schema.json
hawkular-command-gateway/hawkular-command-gateway-api/src/main/resources/schema/RemoveDatasourceResponse.schema.json

Implements EventDestination interface so it triggers an event creation when someone requests an operation for add or delete Datasources.
@jshaughn I think this was the problem of the BZ 1390756 "No MW Provider Event Shown After Deleting Datasource", Could you review this, please? Thanks :) 
Also, I'm not sure if we should implement this for other commands.

Implements EventDestination on Add/Remove Datasource  Command

---

pom.xml

and exclusion for .log files because release builds started failing due to files like hs_err_pid22992.log, generated during a test (probably due to openjdk).

Move license checker exclusions to apply globally

---

vertx/server/src/main/java/org/hawkular/HandlersManager.java

Fix a bug in the scanner of handlers as if hawkular is part of a directory a third party jar passed the filter and it is processed for scanning (which is something we don't want).
So, filter is limited to the jar name, not the full path.

Filter correctly handlers on *hawkular*.jar files

---

vertx/server/src/main/java/org/hawkular/HawkularManager.java

Introduced a HawkularManager utility class for command line invocation of HawkularServer MBean.
It is just a skeleton for status/stop operations but needed to stop properly a server, invoking the chained .stop() calls.
No security implemented yet, it is remote instead of using attach VM utilities to simplify as a) to allow remote operations b) to not deal with the specific of tools.jar per platform.

Skeleton for remote HawkularServer MBean invocation

---

vertx/server/src/main/java/org/hawkular/HandlersManager.java

This PR adds a basic CorsHandler into the baseUrl.
During UI work, a local dev uses a different domain to access into the server and Cors rules are necessary.
Perhaps it can also get necessary in other scenarios and we might want to add more options (restrict the headers, methods, etc) but for now I think is good.

Optional CorsHandler for UI development

---

hawkular-command-gateway/hawkular-command-gateway-api/src/main/resources/schema/ExportJdrRequest.schema.json

Export JDR operation is streaming to the client. It may not make sense
to keep a copy of it in the server node. Adding a property to allow the
client to choose if the report should be kept. Being a boolean variable,
default is to keep a copy.

Adding property to delete JDR report file after export operation ends

---

pom.xml
utils/pom.xml
utils/src/main/java/org/hawkular/commons/log/MsgLogger.java
utils/src/main/java/org/hawkular/commons/log/MsgLogging.java
utils/src/main/java/org/hawkular/commons/properties/HawkularProperties.java

@lucasponce These utils  are currently used in alerts 1.8.  They seem reasonable to keep here.

Add back utils for use by alerts and others.

---

hawkular-inventory-parent/hawkular-inventory-service/src/main/java/org/hawkular/inventory/service/InventoryServiceIspn.java
hawkular-inventory-parent/hawkular-inventory-service/src/main/resources/wildfly-10-jmx-exporter.yml
hawkular-inventory-parent/hawkular-inventory-service/src/test/java/org/hawkular/inventory/service/InventoryRestTest.java
hawkular-inventory-parent/hawkular-inventory-service/src/test/java/org/hawkular/inventory/service/InventoryServiceIspnTest.java

I just want some place to put a jmx exporter config that I configured for our first attempt. This works on wildfly 10.x.
@jotak I found an issue we need to address. Since this just builds the war, the only place I can put it is in WEB-INF/classes (along with the ispn.xml file). However, we want the user to be able to create their own or override this default file. So we need to change the REST endpoints to first look in standalone/configuration as you have it now, however, if the file is not found, look for it in the WAR classloader (and thus will pick up any default files we ship with the war).
This will also help our current distribution model - which as it stands now is just a war and we ask devs to copy the war to any wildfly standalone/deployment folder. Without this new feature, we …

start of jmx exporter configs

---

hawkular-inventory-parent/hawkular-inventory-api/src/main/java/org/hawkular/inventory/api/InventoryService.java
hawkular-inventory-parent/hawkular-inventory-model/src/main/java/org/hawkular/inventory/model/Resource.java
hawkular-inventory-parent/hawkular-inventory-model/src/test/java/org/hawkular/inventory/model/ResourceTest.java
hawkular-inventory-parent/hawkular-inventory-service/src/main/java/org/hawkular/inventory/handlers/InventoryHandlers.java
hawkular-inventory-parent/hawkular-inventory-service/src/main/java/org/hawkular/inventory/service/InventoryServiceIspn.java
hawkular-inventory-parent/hawkular-inventory-service/src/test/java/org/hawkular/inventory/service/InventoryRestTest.java
hawkular-inventory-parent/hawkular-inventory-service/src/test/java/org/hawkular/inventory/service/InventoryServiceIspnTest.java

- Always use plural "resources"
- Use /resources/{id}/tree instead of /resources/tree/{id} (fixing potential conflict)
- Change "rootId" to "isRoot" in data model
- Merge endpoints that return Resources with different filters (get all root, get by type)

Update rest endpoints

---

hawkular-inventory-parent/hawkular-inventory-service/pom.xml
hawkular-inventory-parent/hawkular-inventory-service/src/main/java/org/hawkular/inventory/handlers/InventoryHandlers.java
hawkular-inventory-parent/hawkular-inventory-service/src/main/java/org/hawkular/inventory/handlers/ManifestUtil.java

Adding version on the status endpoint like
```
{"Implementation-Version":"0.9.8.Final-SNAPSHOT","Built-From-Git-SHA1":"d559f689f75ef3936b8dda51dcc053e065d40b1b","status":"UP"}
```
This will help to identify the inventory version in place (thinking on the ruby-client).
Please, @jotak can you take a look ?

Enrich status endpoint with version info

---

hawkular-inventory-parent/hawkular-inventory-model/pom.xml
hawkular-inventory-parent/hawkular-inventory-service/pom.xml
hawkular-inventory-parent/pom.xml
pom.xml

Convert from infinispan-embedded to standard infinispan and hibernate-search jars.  Note that there are some subtleties in the dependency-management to override the WF bom versions.

Convert from infinispan-embedded to standard infinispan

---

hawkular-command-gateway/hawkular-command-gateway-api/src/main/java/org/hawkular/cmdgw/api/MessageUtils.java
hawkular-command-gateway/hawkular-command-gateway-api/src/main/resources/schema/UpdateDatasourceResponse.schema.json

@jmazzitelli, this fixes your reported bug
I think now is in good shape.
As you have seen, the main change is to remove the old inventory API and to change the ResourcePath* per Resource* instead to work with resourcePath and extract the relevant info, now the base is to use feedId and resourceId data.
I think it is reasonable, but let me know if any additional change is needed.

Fix ResourcePathResponse > ResourceResponse changes

---

hawkular-inventory-parent/hawkular-inventory-api/src/main/java/org/hawkular/inventory/api/ResourceNode.java
hawkular-inventory-parent/hawkular-inventory-api/src/main/java/org/hawkular/inventory/api/ResourceWithType.java
hawkular-inventory-parent/hawkular-inventory-api/src/test/java/org/hawkular/inventory/api/JsonTest.java
hawkular-inventory-parent/hawkular-inventory-model/src/main/java/org/hawkular/inventory/model/Resource.java
hawkular-inventory-parent/hawkular-inventory-model/src/test/java/org/hawkular/inventory/model/BuilderTest.java
hawkular-inventory-parent/hawkular-inventory-model/src/test/java/org/hawkular/inventory/model/ResourceTest.java
hawkular-inventory-parent/hawkular-inventory-service/src/main/java/org/hawkular/inventory/service/InventoryServiceIspn.java
hawkular-inventory-parent/hawkular-inventory-service/src/test/java/org/hawkular/inventory/service/InventoryRestTest.java
hawkular-inventory-parent/hawkular-inventory-service/src/test/java/org/hawkular/inventory/service/InventoryServiceIspnTest.java

I listed some pros & cons about using parent versus children in model:
PRO:
- Easier update from the agent: when a resource is added or deleted, no need to search for its parent to update it too. Correctness of the tree not threatened.
- No need for "isRoot" field & index anymore.
CONS:
- Must be indexed to satisfy queries such as: "find all resources whose parent is xxx", typically to build subtree.
- Cannot get children ids from raw resource anymore. So they will not be visible either when getting a resource not in "tree" mode.

Replace children with parent in Resource model

---

hawkular-inventory-parent/hawkular-inventory-api/src/main/java/org/hawkular/inventory/api/InventoryService.java
hawkular-inventory-parent/hawkular-inventory-service/src/main/java/org/hawkular/inventory/handlers/InventoryHandlers.java
hawkular-inventory-parent/hawkular-inventory-service/src/main/java/org/hawkular/inventory/service/InventoryServiceIspn.java
hawkular-inventory-parent/hawkular-inventory-service/src/test/java/org/hawkular/inventory/service/InventoryRestTest.java
hawkular-inventory-parent/hawkular-inventory-service/src/test/java/org/hawkular/inventory/service/InventoryServiceIspnTest.java

I know there is already getTree but this helps the UI expand a tree incrementally, and I think it is generally useful to retrieve only immediate children.
@jotak Please review, thanks.

Add Service to just get direct child resources of a parent.

---

hawkular-inventory-parent/hawkular-inventory-api/src/main/java/org/hawkular/inventory/api/Inventory.java
hawkular-inventory-parent/hawkular-inventory-api/src/main/java/org/hawkular/inventory/api/InventoryService.java
hawkular-inventory-parent/hawkular-inventory-service/pom.xml
hawkular-inventory-parent/hawkular-inventory-service/src/main/java/org/hawkular/inventory/handlers/InventoryHandlers.java
hawkular-inventory-parent/hawkular-inventory-service/src/main/java/org/hawkular/inventory/service/InventoryServiceIspn.java
hawkular-inventory-parent/hawkular-inventory-service/src/test/java/org/hawkular/inventory/service/InventoryPerfTest.java
hawkular-inventory-parent/hawkular-inventory-service/src/test/java/org/hawkular/inventory/service/InventoryRestTest.java
hawkular-inventory-parent/hawkular-inventory-service/src/test/java/org/hawkular/inventory/service/InventoryServiceIspnTest.java
hawkular-inventory-parent/hawkular-inventory-service/src/test/java/org/hawkular/inventory/service/Resources.java
hawkular-inventory-parent/pom.xml
utils/pom.xml
utils/src/main/java/org/hawkular/commons/json/JsonUtil.java

In the same time, refactor tests to separate perf & rest tests so that "export" is not run after perf tests.
New common file for test resources definitions

Add export endpoint + split tests

---

hawkular-inventory-parent/hawkular-inventory-model/pom.xml
hawkular-inventory-parent/hawkular-inventory-model/src/main/java/org/hawkular/inventory/model/Resource.java
hawkular-inventory-parent/hawkular-inventory-model/src/main/java/org/hawkular/inventory/model/ResourceType.java
hawkular-inventory-parent/hawkular-inventory-service/pom.xml
hawkular-inventory-parent/hawkular-inventory-service/src/main/java/org/hawkular/inventory/service/InventoryServiceIspn.java
hawkular-inventory-parent/hawkular-inventory-service/src/main/java/org/hawkular/inventory/service/ispn/IspnResource.java
hawkular-inventory-parent/hawkular-inventory-service/src/main/java/org/hawkular/inventory/service/ispn/IspnResourceType.java
hawkular-inventory-parent/hawkular-inventory-service/src/main/resources/hawkular-inventory-ispn.xml
hawkular-inventory-parent/hawkular-inventory-service/src/test/resources/hawkular-inventory-ispn-test.xml

@jotak, this is related our discussion on friday.
This approach was followed in Alerting 2.x, basically the idea is to separate the object used to store in the backend vs the object used in the Java API, and make it inmutable.
Also, this PR fixes performance tests and makes them mandatory in the profile.

Inmutable objects in backend and fixes in performance tests

---

hawkular-command-gateway/hawkular-command-gateway-api/src/main/resources/schema/UpdateCollectionIntervalsRequest.schema.json
hawkular-command-gateway/hawkular-command-gateway-api/src/main/resources/schema/UpdateCollectionIntervalsResponse.schema.json
hawkular-command-gateway/hawkular-command-gateway-api/src/main/resources/schema/UpdateDatasourceRequest.schema.json

In the context of Prometheus, we dropped collection interval commands.
Restoring these classes to enable CmdGw sync correctly with the agent.

Bring back UpdateCollectionIntervals commands

---

hawkular-inventory-parent/hawkular-inventory-service/src/main/resources/wildfly-10-jmx-exporter.yml

Since Prometheus doesn't support string or avail metrics, if a deployment status is OK, the metric has a value of "1" and if it's stopped or failed to deploy its metric value is "0". Such as:
```
wildfly_deployment_availability{name="kitchensink-ear.ear",} 1.0
wildfly_deployment_availability{name="test-little-1.0.0.ear",} 1.0
wildfly_deployment_availability{name="test-simple-1.0.0.war",} 0.0
```

Add avail metrics for deployments.

---

hawkular-inventory-parent/hawkular-inventory-ui/pom.xml
hawkular-inventory-parent/pom.xml

This is primarily to speed up dev builds and as such the ui is still built by default.

Can now build -P-ui to optionally omit the ui build. 

---

hawkular-inventory-parent/hawkular-inventory-api/src/main/java/org/hawkular/inventory/api/InventoryService.java
hawkular-inventory-parent/hawkular-inventory-itest/pom.xml
hawkular-inventory-parent/hawkular-inventory-itest/src/test/java/org/hawkular/inventory/handlers/InventoryRestTest.java
hawkular-inventory-parent/hawkular-inventory-service/src/main/java/org/hawkular/inventory/log/MsgLogger.java
hawkular-inventory-parent/hawkular-inventory-service/src/main/java/org/hawkular/inventory/service/InventoryConfig.java
hawkular-inventory-parent/hawkular-inventory-service/src/main/java/org/hawkular/inventory/service/InventoryConfigPath.java
hawkular-inventory-parent/hawkular-inventory-service/src/main/java/org/hawkular/inventory/service/InventoryServiceIspn.java
hawkular-inventory-parent/hawkular-inventory-service/src/main/java/org/hawkular/inventory/service/ScrapeConfig.java
hawkular-inventory-parent/hawkular-inventory-service/src/main/java/org/hawkular/inventory/service/ScrapeConfigInit.java
hawkular-inventory-parent/hawkular-inventory-service/src/main/java/org/hawkular/inventory/service/ScrapeLocation.java
hawkular-inventory-parent/hawkular-inventory-service/src/main/resources/hawkular-inventory-prometheus-scrape-config.yaml
hawkular-inventory-parent/hawkular-inventory-service/src/test/java/org/hawkular/inventory/service/InventoryServiceIspnTest.java
hawkular-inventory-parent/hawkular-inventory-service/src/test/java/org/hawkular/inventory/service/ScrapeConfigTest.java
hawkular-inventory-parent/hawkular-inventory-service/src/test/resources/hawkular-inventory-prometheus-scrape-config.yaml
utils/pom.xml
utils/src/main/java/org/hawkular/commons/json/JsonUtil.java

As discussed in HAWKULAR-1292 this PRs filters inventory and when an agent is added, it will create the Prometheus configuration file.
Then, the agent has not to invoke this operation, this happens on registration (or modification) of agents in inventory.
This filter is cheap in terms of performance, so I don't see a problem here.
Also, filters are defined from configuration.
Today there is the assumption that there is a single p8s server, and probably very soon we will play with other topologies, then this scheme can be used to maintain the state which agent is managed  in which p8s server.

HAWKULAR-1292 Have Inventory update the Prometheus scrape endpoints

---

hawkular-inventory-parent/hawkular-inventory-itest/src/test/java/org/hawkular/inventory/handlers/InventoryRestTest.java
hawkular-inventory-parent/hawkular-inventory-service/src/main/java/org/hawkular/inventory/log/MsgLogger.java
hawkular-inventory-parent/hawkular-inventory-service/src/main/java/org/hawkular/inventory/service/InventoryConfig.java
hawkular-inventory-parent/hawkular-inventory-service/src/main/java/org/hawkular/inventory/service/InventoryServiceIspn.java
hawkular-inventory-parent/hawkular-inventory-service/src/main/resources/hawkular-inventory-prometheus-scrape-config.yaml
hawkular-inventory-parent/hawkular-inventory-service/src/test/java/org/hawkular/inventory/service/InventoryServiceIspnTest.java
hawkular-inventory-parent/hawkular-inventory-service/src/test/java/org/hawkular/inventory/service/ScrapeConfigTest.java
hawkular-inventory-parent/hawkular-inventory-service/src/test/resources/hawkular-inventory-prometheus-scrape-config.yaml

This is part of HAWKULAR-1292
The name of the agent type is "Hawkular Java Agent".
This also adds come info log msgs at startup to know where its getting the config file.
Also puts in some checks to ensure no one tries to access filenames with ".." in the paths.

fix metrics endpoint filter

---

hawkular-inventory-parent/hawkular-inventory-service/src/main/java/org/hawkular/inventory/service/InventoryConfig.java

InventoryConfig performs some tasks at init phase that might need more time than standard 5s, so, increasing this timeout will help on slow environments like travis where we have seen this issue.

HAWKULAR-1325 Increase wait time for initialization

---

hawkular-inventory-parent/hawkular-inventory-service/src/main/resources/EAP6-inventory.yml
hawkular-inventory-parent/hawkular-inventory-service/src/main/resources/WF10-inventory.yml

This is a PR that doesn't change any functionality - but it does clean up the yaml config files. There are lots of trivial changes here (we had some weird spacing/indentation in many values and quoted things we didn't need to) - just doing this all at once to make the yaml files more consistent and will avoid irrelevant diffs later if this gets fixed little by little. Just do it all now in this PR.
I'll do the same for the agent yaml files too.

clean up yaml

---

hawkular-command-gateway/hawkular-command-gateway-api/src/main/resources/schema/AddJdbcDriverResponse.schema.json
hawkular-command-gateway/hawkular-command-gateway-api/src/main/resources/schema/RemoveJdbcDriverResponse.schema.json

When I added the JDBC event mapping for MIQ in the related PR, I didn't know JDBC responses are not reaching the CommandEventListener, let's fix it.
I'm not sure if this is the proper fix, please correct me if I'm wrong. I'm trying to test it, but without success so far (I'm not able to build the hawkular-services properly). Can you please help me to test that?
Related to: https://github.com/hawkular/hawkular-services/pull/191
Fixes: [BUG 1515476](https://bugzilla.redhat.com/show_bug.cgi?id=1515476)
cc @jshaughn

Enable JDBC events to reach CommandEventListener

---

hawkular-command-gateway/hawkular-command-gateway-war/src/main/java/org/hawkular/cmdgw/command/ws/server/FeedWebSocket.java

HawkularTopic was used in BackfillCache feature which is no longer on HAWKULAR-1275, so sending this message on websocket close is not necessary and might cause errors on server log.

HAWKULAR-1339 Remove msg message to HawkularTopic
